
[server]
headless = true
address = "0.0.0.0"
port = 5000
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#f3770c"
backgroundColor = "#fff9e6"
secondaryBackgroundColor = "#fff9f0"
textColor = "#3a1d0d"
